FROM public.ecr.aws/docker/library/rust:1.85.1-alpine3.21 AS init-builder
WORKDIR /library-checker-init
COPY init /library-checker-init
RUN cargo build --release --target=x86_64-unknown-linux-musl

FROM public.ecr.aws/docker/library/julia:1.11.4

COPY --from=init-builder /library-checker-init/target/x86_64-unknown-linux-musl/release/library-checker-init /usr/bin

LABEL library-checker-image=true
