[[langs]]
    id = "cpp"
    name = "C++23"
    version = "GCC 14.2 + AC Library(1.5.1)"
    source = "main.cpp"    
    image_name = "library-checker-images-gcc"
    compile = ["g++", "-O2", "-std=c++23", "-DEVAL", "-march=native", "-o", "main", "main.cpp", "-I", "/opt/ac-library"]
    exec = ["./main"]
[[langs]]
    id = "clang"
    name = "C++23(clang)"
    version = "CLANG 18 + AC Library(1.5.1)"
    source = "main.cpp"    
    image_name = "library-checker-images-clang"
    compile = ["clang++", "-O2", "-std=c++23", "-DEVAL", "-march=native", "-o", "main", "main.cpp", "-I", "/opt/ac-library"]
    exec = ["./main"]
[[langs]]
    id = "python3"
    name = "Python3"
    version = "python3.12 + numpy + scipy"
    source = "main.py"
    image_name = "library-checker-images-python3"
    compile = ["sh", "-c", "echo | python3 -c 'import main.py' || :"]
    exec = ["python3", "main.py"]
[[langs]]
    id = "pypy3"
    name = "PyPy3"
    version = "pypy3.11-7.3.19"
    source = "main.py"
    image_name = "library-checker-images-pypy"
    compile = ["pypy3", "-c", "'print(1)'"]
    exec = ["pypy3", "main.py"]
[[langs]]
    id = "go"
    name = "Go"
    version = "go 1.24.1"
    source = "main.go"
    image_name = "library-checker-images-golang"
    compile = ["go", "build", "main.go"]
    exec = ["./main"]
[[langs]]
    id = "ruby"
    name = "Ruby"
    version = "ruby 3.4.2"
    source = "main.rb"
    image_name = "library-checker-images-ruby"
    compile = ["ruby", "-w", "-c", "main.rb"]
    exec = ["ruby", "main.rb"]
[[langs]]
    id = "julia"
    name = "Julia"
    version = "julia 1.11.4"
    source = "Main.jl"
    image_name = "library-checker-images-julia"
    compile = ["julia", "-e", "Meta.parse(\"begin \" * read(\"Main.jl\",String) * \" end\")"]
    exec = ["julia", "Main.jl"]
[[langs]]
    id = "scheme"
    name = "Scheme (Gauche)"
    version = "gauche 0.9.15"
    source = "Main.scm"
    image_name = "library-checker-images-scheme"
    compile = ["touch", "ok"]
    exec = ["gosh", "Main.scm"]
